HYPRGRAPHICS_VERSION = 0.1.6
HYPRGRAPHICS_SITE = $(call github,hyprwm,hyprgraphics,v$(HYPRGRAPHICS_VERSION))
HYPRGRAPHICS_LICENSE = BSD-3-Clause
HYPRGRAPHICS_LICENSE_FILES = LICENSE
HYPRGRAPHICS_DEPENDENCIES = cairo hyprutils jpeg libpng pango webp

HYPRGRAPHICS_INSTALL_STAGING = YES

$(eval $(cmake-package))
