HYPRLAND_PROTOCOLS_VERSION = 0.6.2
HYPRLAND_PROTOCOLS_SITE = $(call github,hyprwm,hyprland-protocols,v$(HYPRLAND_PROTOCOLS_VERSION))
HYPRLAND_PROTOCOLS_LICENSE = BSD-3-Clause
HYPRLAND_PROTOCOLS_LICENSE_FILES = LICENSE
HYPRLAND_PROTOCOLS_INSTALL_STAGING = YES
HYPRLAND_PROTOCOLS_INSTALL_TARGET = NO
HYPRLAND_PROTOCOLS_DEPENDENCIES = host-pkgconf

define HYPRLAND_PROTOCOLS_INSTALL_STAGING_PC
	$(INSTALL) -D -m 0644 $(HYPRLAND_PROTOCOLS_PKGDIR)/hyprland-protocols.pc \
		$(STAGING_DIR)/usr/lib/pkgconfig/hyprland-protocols.pc
endef

HYPRLAND_PROTOCOLS_POST_INSTALL_STAGING_HOOKS += HYPRLAND_PROTOCOLS_INSTALL_STAGING_PC

$(eval $(meson-package))
