HYPRCURSOR_VERSION = 0.1.13
HYPRCURSOR_SITE = $(call github,hyprwm,hyprcursor,v$(HYPRCURSOR_VERSION))
HYPRCURSOR_LICENSE = BSD-3-Clause
HYPRCURSOR_LICENSE_FILES = LICENSE
HYPRCURSOR_DEPENDENCIES = cairo hyprlang libzip librsvg tomlplusplus

HYPRCURSOR_SUPPORTS_IN_SOURCE_BUILD = NO

HYPRCURSOR_INSTALL_STAGING = YES

HYPRCURSOR_CONF_OPTS = \
	-DCMAKE_EXE_LINKER_FLAGS="$(TARGET_LDFLAGS) -Wl,--allow-shlib-undefined"

$(eval $(cmake-package))
