
FASTFETCH_VERSION = 2.69.0
FASTFETCH_SITE = $(call github,fastfetch-cli,fastfetch,$(FASTFETCH_VERSION))
FASTFETCH_LICENSE = MIT
FASTFETCH_LICENSE_FILES = LICENSE

FASTFETCH_CONF_OPTS = \
	-DBUILD_FLASHFETCH=OFF \
	-DENABLE_IMAGE_LOGO=OFF \
	-DENABLE_EGL=OFF \
	-DENABLE_GLX=OFF \
	-DENABLE_LUA=OFF \
	-DENABLE_QUICKJS=OFF \
	-DENABLE_LIBZFS=OFF \
	-DENABLE_LTO=OFF \
	-DIS_MUSL=$(if $(BR2_TOOLCHAIN_USES_MUSL),ON,OFF)

$(eval $(cmake-package))
