HYPRWAYLAND_SCANNER_VERSION = 0.4.4
HYPRWAYLAND_SCANNER_SITE = $(call github,hyprwm,hyprwayland-scanner,v$(HYPRWAYLAND_SCANNER_VERSION))
HYPRWAYLAND_SCANNER_LICENSE = BSD-3-Clause
HYPRWAYLAND_SCANNER_LICENSE_FILES = LICENSE
HYPRWAYLAND_SCANNER_DEPENDENCIES = host-pugixml

HOST_HYPRWAYLAND_SCANNER_DEPENDENCIES = host-pugixml

$(eval $(host-cmake-package))
