TOMLPLUSPLUS_VERSION = 3.4.0
TOMLPLUSPLUS_SITE = $(call github,marzer,tomlplusplus,v$(TOMLPLUSPLUS_VERSION))
TOMLPLUSPLUS_LICENSE = MIT
TOMLPLUSPLUS_LICENSE_FILES = LICENSE
TOMLPLUSPLUS_INSTALL_STAGING = YES
TOMLPLUSPLUS_DEPENDENCIES = host-pkgconf

define TOMLPLUSPLUS_INSTALL_STAGING_PC
	$(INSTALL) -D -m 0644 $(TOMLPLUSPLUS_PKGDIR)/tomlplusplus.pc \
		$(STAGING_DIR)/usr/lib/pkgconfig/tomlplusplus.pc
endef

TOMLPLUSPLUS_POST_INSTALL_STAGING_HOOKS += TOMLPLUSPLUS_INSTALL_STAGING_PC

$(eval $(cmake-package))

