HYPRUTILS_VERSION = 0.9.0
HYPRUTILS_SITE = $(call github,hyprwm,hyprutils,v$(HYPRUTILS_VERSION))
HYPRUTILS_LICENSE = BSD-3-Clause
HYPRUTILS_LICENSE_FILES = LICENSE
HYPRUTILS_DEPENDENCIES = pixman
HYPRUTILS_INSTALL_STAGING = YES

$(eval $(cmake-package))
