UDIS86_VERSION = 1.7.2
UDIS86_SITE = $(call github,canihavesomecoffee,udis86,v$(UDIS86_VERSION))
UDIS86_LICENSE = BSD-3-Clause
UDIS86_LICENSE_FILES = LICENSE
UDIS86_DEPENDENCIES = host-python3
UDIS86_INSTALL_STAGING = YES
UDIS86_AUTORECONF = YES
UDIS86_CONF_ENV = PYTHON="$(HOST_DIR)/bin/python3"

define UDIS86_INSTALL_STAGING_PC
	$(INSTALL) -D -m 0644 $(UDIS86_PKGDIR)/udis86.pc \
		$(STAGING_DIR)/usr/lib/pkgconfig/udis86.pc
endef

UDIS86_POST_INSTALL_STAGING_HOOKS += UDIS86_INSTALL_STAGING_PC

$(eval $(autotools-package))

